import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { AnimatedPage } from "@/components/animated-page";

export default function DashboardHealth() {
  return (
    <AnimatedPage className="space-y-6">
      <div>
        <h1 className="text-2xl font-semibold text-foreground">Health</h1>
        <p className="text-sm text-muted-foreground">
          Habits, training & meal plans, workload balance
        </p>
      </div>

      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        <Card className="border-white/[0.03] bg-card">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">Recovery score</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-foreground">82%</div>
            <p className="text-xs text-muted-foreground">Good</p>
          </CardContent>
        </Card>
        <Card className="border-white/[0.03] bg-card">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">Habits (7d)</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-foreground">5/7</div>
          </CardContent>
        </Card>
        <Card className="border-white/[0.03] bg-card">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">Workload</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-sm text-muted-foreground">Balanced</div>
          </CardContent>
        </Card>
      </div>

      <div className="grid gap-4 md:grid-cols-2">
        <Card className="border-white/[0.03] bg-card">
          <CardHeader>
            <CardTitle>Habits</CardTitle>
            <p className="text-sm text-muted-foreground">Daily check-in, agent coaching</p>
          </CardHeader>
          <CardContent>
            <Button variant="outline" size="sm">View habits</Button>
          </CardContent>
        </Card>
        <Card className="border-white/[0.03] bg-card">
          <CardHeader>
            <CardTitle>Training & meal plan</CardTitle>
            <p className="text-sm text-muted-foreground">Generated by agent</p>
          </CardHeader>
          <CardContent>
            <Button variant="outline" size="sm">View plan</Button>
          </CardContent>
        </Card>
      </div>
    </AnimatedPage>
  );
}
