/**
 * Mock Content LLM Adapter — used when VITE_API_URL is not set or VITE_USE_MOCK_CONTENT is true.
 */

import type {
  DraftContentPayload,
  DraftContentResult,
  EditContentPayload,
  EditContentResult,
  ResearchAssistPayload,
  ResearchAssistResult,
  SEOSuggestionsPayload,
  SEOSuggestionsResult,
  SafetyCheckPayload,
  SafetyCheckResult,
} from "@/types/content-llm";

const MOCK_DELAY_MS = 600;

function delay(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}

export async function mockDraftContent(
  input: DraftContentPayload
): Promise<DraftContentResult & { debugInfo?: Record<string, unknown> }> {
  await delay(MOCK_DELAY_MS);
  const idea = input?.idea ?? "";
  if (!idea.trim()) return { draft: "", promptsUsed: [], debugInfo: {} };
  const tone = input?.constraints?.tone ?? "professional";
  return {
    draft: `[LLM Draft - ${tone} tone]\n\nBased on your idea: "${idea.slice(0, 80)}${idea.length > 80 ? "..." : ""}"\n\nHere is an expanded draft. In production, this would be generated by the Content LLM Adapter via OpenAI API with content constraints, safety filters, and audit traces.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.`,
    promptsUsed: ["draft-from-idea"],
    debugInfo: { mock: true },
  };
}

export async function mockEditContent(
  input: EditContentPayload
): Promise<EditContentResult> {
  await delay(MOCK_DELAY_MS);
  const edits = typeof input?.edits === "string" ? input.edits : JSON.stringify(input?.edits ?? "");
  const content = typeof input?.content === "string" ? input.content : "";
  const tone = input?.constraints?.tone ?? "professional";
  const base = content || "No content";
  return {
    editedDraft: `[LLM Edited - ${tone}]\n\n${base.slice(0, 200)}${base.length > 200 ? "..." : ""}\n\n[Applied: ${edits.slice(0, 60)}...]`,
    changes: ["tone-adjustment", "content-refinement"],
  };
}

export async function mockResearchAssist(
  input: ResearchAssistPayload
): Promise<ResearchAssistResult> {
  await delay(MOCK_DELAY_MS);
  const topic = input?.topic ?? "";
  if (!topic.trim()) return { notes: [], sources: [] };
  return {
    notes: [
      `Key finding 1 for "${topic}": Relevant industry data and trends.`,
      `Key finding 2: Competitor analysis and market positioning.`,
      `Key finding 3: Best practices and recommendations.`,
    ],
    sources: [
      "https://example.com/source1",
      "https://example.com/source2",
    ],
  };
}

export async function mockSEOSuggestions(
  input: SEOSuggestionsPayload
): Promise<SEOSuggestionsResult> {
  await delay(MOCK_DELAY_MS);
  const content = input?.content ?? "";
  const keywords = input?.targetKeywords ?? [];
  const extracted = content.slice(0, 100).toLowerCase().split(/\s+/).filter(Boolean);
  const suggested = [...new Set([...keywords, ...extracted.slice(0, 5)])].slice(0, 8);
  return {
    seoMeta: {
      keywords: suggested,
      metaDescription: content.slice(0, 155) + (content.length > 155 ? "..." : ""),
      readability: 72,
    },
    recommendations: [
      "Add primary keyword in the first 100 characters.",
      "Include 2-3 secondary keywords naturally.",
      "Aim for 150-160 characters in meta description.",
    ],
  };
}

export async function mockSafetyCheck(
  input: SafetyCheckPayload
): Promise<SafetyCheckResult> {
  await delay(200);
  const content = input?.content ?? "";
  if (!content.trim()) return { allowed: true, rationale: "Empty content" };
  const blocked = /blocked|forbidden|harmful/i.test(content);
  return {
    allowed: !blocked,
    rationale: blocked
      ? "Content contains terms that may violate policy."
      : "Content passed safety checks.",
  };
}
